# Generated by Django 4.2.5 on 2025-08-22 05:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detection_type', models.CharField(choices=[('image', 'Image Upload'), ('webcam', 'Webcam'), ('video', 'Video File')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmotionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('emotions', models.JSONField()),
                ('face_coordinates', models.JSONField()),
                ('dominant_emotion', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detector.detectionsession')),
            ],
        ),
    ]
