# Generated by Django 4.2.5 on 2025-09-13 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominant_emotion', models.CharField(max_length=20)),
                ('emotion_scores', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='detectionsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='detectionsession',
            name='detection_type',
            field=models.CharField(choices=[('webcam', 'Webcam Detection'), ('upload', 'Image Upload')], max_length=10),
        ),
        migrations.DeleteModel(
            name='EmotionResult',
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='detector.detectionsession'),
        ),
    ]
